### ISSUE TITLE
BD: Listas

### ISSUE THREAD

**Issue by estebansalas18** [cbasguti/ahorra_app#7]
El producto que se añade a la lista debe guardarse solamente con la información de la tienda elegida, es decir, si lo añadí con la tienda que tiene el precio mas caro, el producto debe tener ese precio en la lista, y no actualizarse al precio mas barato

Si agrego el mismo producto de dos tiendas diferentes este debe ser capaz de unificarse y dejar la tienda con el precio mas barato

**Comment by estebansalas18** [comment]
Además de esto, debemos agregar una funcionalidad que permita actualizar las listas en tiempo real, con el fin de que si estoy editando una lista y agrego mas productos, la cantidad de estos se debe ver al instante en la lista, al igual que el precio total de la lista

**Comment by cbasguti** [comment]
> Si agrego el mismo producto de dos tiendas diferentes este debe ser capaz de unificarse y dejar la tienda con el precio mas barato

Esto creo que se debería resolver con el otro issue #8
